# -*- coding: utf-8 -*-
"""BRAX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h97TZXt8F4ffJA_0WfkZ2I8TjnJl4TrF

The first two sections are for my own understanding, the actual work starts from ""Create Walls from track boundaries""

# Builds the Track from Centerlines
"""

import pandas as pd
import numpy as np

centerline_path = '/content/Budapest_centerline.csv'
centerline_data = pd.read_csv(centerline_path)
centerline_data.columns = centerline_data.columns.str.strip().str.replace('# ', '')

x_left, y_left = [], []
x_right, y_right = [], []

for i in range(len(centerline_data) - 1):

    x1, y1 = centerline_data.loc[i, 'x_m'], centerline_data.loc[i, 'y_m']
    x2, y2 = centerline_data.loc[i + 1, 'x_m'], centerline_data.loc[i + 1, 'y_m']
    dx, dy = x2 - x1, y2 - y1
    length = np.sqrt(dx**2 + dy**2)
    normal_x, normal_y = -dy / length, dx / length
    width_right = centerline_data.loc[i, 'w_tr_right_m']
    width_left = centerline_data.loc[i, 'w_tr_left_m']

    x_left.append(x1 + normal_x * width_left)
    y_left.append(y1 + normal_y * width_left)
    x_right.append(x1 - normal_x * width_right)
    y_right.append(y1 - normal_y * width_right)

x1, y1 = centerline_data.loc[len(centerline_data) - 1, 'x_m'], centerline_data.loc[len(centerline_data) - 1, 'y_m']
x_left.append(x1 + normal_x * width_left)
y_left.append(y1 + normal_y * width_left)
x_right.append(x1 - normal_x * width_right)
y_right.append(y1 - normal_y * width_right)

boundary_data = pd.DataFrame({
    'x_left': x_left,
    'y_left': y_left,
    'x_right': x_right,
    'y_right': y_right
})

boundary_csv_path = 'track_boundaries.csv'
boundary_data.to_csv(boundary_csv_path, index=False)

boundary_data.head()

"""# Visualize the Track



"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

centerline_path = '/content/Budapest_centerline.csv'
centerline_data = pd.read_csv(centerline_path)
centerline_data.columns = centerline_data.columns.str.strip().str.replace('# ', '')

x_left, y_left = [], []
x_right, y_right = [], []

for i in range(len(centerline_data) - 1):
    x1, y1 = centerline_data.loc[i, 'x_m'], centerline_data.loc[i, 'y_m']
    x2, y2 = centerline_data.loc[i + 1, 'x_m'], centerline_data.loc[i + 1, 'y_m']
    dx, dy = x2 - x1, y2 - y1
    length = np.sqrt(dx**2 + dy**2)
    normal_x, normal_y = -dy / length, dx / length

    width_right = centerline_data.loc[i, 'w_tr_right_m']
    width_left = centerline_data.loc[i, 'w_tr_left_m']

    x_left.append(x1 + normal_x * width_left)
    y_left.append(y1 + normal_y * width_left)
    x_right.append(x1 - normal_x * width_right)
    y_right.append(y1 - normal_y * width_right)

x1, y1 = centerline_data.loc[len(centerline_data) - 1, 'x_m'], centerline_data.loc[len(centerline_data) - 1, 'y_m']
x_left.append(x1 + normal_x * width_left)
y_left.append(y1 + normal_y * width_left)
x_right.append(x1 - normal_x * width_right)
y_right.append(y1 - normal_y * width_right)

boundary_data = pd.DataFrame({
    'x_left': x_left,
    'y_left': y_left,
    'x_right': x_right,
    'y_right': y_right
})

plt.figure(figsize=(12, 8))

plt.plot(centerline_data['x_m'], centerline_data['y_m'], 'bo', label='Centerline', color='blue')

plt.plot(boundary_data['x_left'], boundary_data['y_left'], 'go', label='Left Boundary', color='green')
plt.plot(boundary_data['x_right'], boundary_data['y_right'], 'ro', label='Right Boundary', color='red')

plt.title('Track Boundaries and Centerline')
plt.axis('equal')
plt.xlabel('X (meters)')
plt.ylabel('Y (meters)')
plt.xlim(0,20)
plt.ylim(0,20)
plt.legend()
plt.grid(True)

plt.show()

o

"""# Create Walls from track boundaries

## Install BRAX
"""

# prompt: install brax and clear the output after
from IPython.display import clear_output

!pip install brax
!pip install mujoco
!pip install mujoco_mjx

clear_output()

"""## XML CREATER

Here the kinematic and physical tree are defined in an XML file.

To run it you will need an csv file of the track uploaded in colab, you can get them from here "https://github.com/f1tenth/f1tenth_racetracks".

You will only need the track centerlines!

Please adjust the csv path accordingly.
"""

data_test = pd.read_csv(csv_path)

data_test

import pandas as pd
import xml.etree.ElementTree as ET
from xml.dom import minidom
import numpy as np

def create_track_boundaries_from_csv(csv_path, output_xml_path):
    data = pd.read_csv(csv_path)
    data.columns = data.columns.str.strip().str.replace('# ', '')

    required_columns = {'x_m', 'y_m', 'w_tr_right_m', 'w_tr_left_m'}
    if not required_columns.issubset(data.columns):
        raise ValueError(f"CSV file must contain columns: {required_columns}")

    # Create the element
    mujoco = ET.Element('mujoco', model="track_env")

    # Add compiler and option elements
    compiler = ET.SubElement(mujoco, 'compiler', angle="degree", coordinate="local", inertiafromgeom="true")
    option = ET.SubElement(mujoco, 'option', timestep="0.01", gravity="0 0 0", iterations="20", integrator="Euler")

    # Add default elements
    default = ET.SubElement(mujoco, 'default')
    joint = ET.SubElement(default, 'joint', armature="0.04", damping="1", limited="true")
    geom = ET.SubElement(default, 'geom', contype="0", conaffinity="0", condim="3", density="5.0", friction="0 0 0", rgba="0.4 0.33 0.26 1.0")

    # Add asset elements
    asset = ET.SubElement(mujoco, 'asset')
    texture_skybox = ET.SubElement(asset, 'texture', builtin="gradient", height="100", rgb1="1 1 1", rgb2="0 0 0", type="skybox", width="100")
    texture_geom = ET.SubElement(asset, 'texture', builtin="flat", height="1278", mark="cross", markrgb="1 1 1", name="texgeom", random="0.01", rgb1="0.8 0.6 0.4", rgb2="0.8 0.6 0.4", type="cube", width="127")
    texture_plane = ET.SubElement(asset, 'texture', builtin="checker", height="100", name="texplane", rgb1="0 0 0", rgb2="0.8 0.8 0.8", type="2d", width="100")
    material_plane = ET.SubElement(asset, 'material', name="MatPlane", reflectance="0.5", shininess="1", specular="1", texrepeat="60 60", texture="texplane")
    material_geom = ET.SubElement(asset, 'material', name="geom", texture="texgeom", texuniform="true")

    # Add worldbody elements
    worldbody = ET.SubElement(mujoco, 'worldbody')
    light = ET.SubElement(worldbody, 'light', cutoff="100", diffuse="1 1 1", dir="-0 0 -1.3", directional="true", exponent="1", pos="0 0 1.3", specular=".1 .1 .1")
    floor = ET.SubElement(worldbody, 'geom', conaffinity="0", condim="1", material="MatPlane", name="floor", pos="0 0 0", size="400 400 0.1", type="plane", rgba="0.5 0.5 0.5 1")

    # Add car element
    car_body = ET.SubElement(worldbody, 'body', name="car", pos="0 0 1.2")
    joint = ET.SubElement(car_body, 'joint', type="free")

    # Car box (main body)
    car_geom = ET.SubElement(car_body, 'geom', size="0.2 0.8 0.15", type="box", rgba="0 0 0 1", quat= "0.0 1.0 0.0 0.0")


    wall_height = 1.5  # Arbitrary height of the walls
    wall_thickness = 0.1  # Small thickness for the walls

    # Function to calculate angle for wall orientation
    def calculate_angle(x1, y1, x2, y2):
        # return np.arctan2(x2 - x1, y2 - y1)
        return np.arctan2(y2 - y1, x2 - x1)

    # Function to add additional points using interpolation
    def interpolate_points(x1, y1, x2, y2, num_points):
        return np.linspace(x1, x2, num_points), np.linspace(y1, y2, num_points)

    # Function to calculate wall segment properties
    def calculate_wall_segment(x1, y1, x2, y2, angle, side, width):
        if side == "left":
            x1 += width * np.cos(angle + np.pi / 2)
            y1 += width * np.sin(angle + np.pi / 2)
            x2 += width * np.cos(angle + np.pi / 2)
            y2 += width * np.sin(angle + np.pi / 2)
        else:
            x1 -= width * np.cos(angle + np.pi / 2)
            y1 -= width * np.sin(angle + np.pi / 2)
            x2 -= width * np.cos(angle + np.pi / 2)
            y2 -= width * np.sin(angle + np.pi / 2)

        pos = f'{(x1 + x2) / 2} {(y1 + y2) / 2} {wall_height / 2}'
        size = f'{((x2 - x1)**2 + (y2 - y1)**2)**0.5 / 2} {wall_thickness / 2} {wall_height / 2}'
        # size = f'{wall_thickness / 2} {((x2 - x1)**2 + (y2 - y1)**2)**0.5 / 2} {wall_height / 2}'
        quat = f'{np.cos(angle / 2)} 0 0 {np.sin(angle / 2)}'
        # quat = f'{np.sin(angle / 2)} 0 0 {np.cos(angle / 2)}'
        return pos, size, quat

    # Add track boundaries as continuous walls with interpolation
    num_interpolation_points = 2  # Number of points to interpolate between each pair of points
    for i in range(len(data) - 1):
        x1, y1 = data.loc[i, 'x_m'], data.loc[i, 'y_m']
        x2, y2 = data.loc[i + 1, 'x_m'], data.loc[i + 1, 'y_m']
        angle = calculate_angle(x1, y1, x2, y2)

        x_interp_left, y_interp_left = interpolate_points(
            x1, y1, x2, y2, num_interpolation_points
        )
        x_interp_right, y_interp_right = interpolate_points(
            x1, y1, x2, y2, num_interpolation_points
        )

        for j in range(num_interpolation_points - 1):
            left_pos, left_size, left_quat = calculate_wall_segment(
                x_interp_left[j], y_interp_left[j], x_interp_left[j + 1], y_interp_left[j + 1], angle, "left", data.loc[i, 'w_tr_left_m']
            )
            right_pos, right_size, right_quat = calculate_wall_segment(
                x_interp_right[j], y_interp_right[j], x_interp_right[j + 1], y_interp_right[j + 1], angle, "right", data.loc[i, 'w_tr_right_m']
            )

            # Left wall curve segment
            left_wall = ET.SubElement(worldbody, 'geom', {
                'type': 'box',
                'pos': left_pos,
                'size': left_size,
                'quat': left_quat,
                'rgba': '1 0 0 1',
                'conaffinity': '1',
                'condim': '1'
            })

            # Right wall curve segment
            right_wall = ET.SubElement(worldbody, 'geom', {
                'type': 'box',
                'pos': right_pos,
                'size': right_size,
                'quat': right_quat,
                'rgba': '0 0 1 1',
                'conaffinity': '1',
                'condim': '1'
            })

    # Create the XML tree and write it to a file with pretty print
    xml_str = ET.tostring(mujoco, encoding='utf-8')
    parsed_xml = minidom.parseString(xml_str)
    pretty_xml_as_string = parsed_xml.toprettyxml()

    with open(output_xml_path, 'w') as f:
        f.write(pretty_xml_as_string)

# Example usage
csv_path = 'Budapest_centerline.csv'
output_xml_path = 'track_env.xml'
create_track_boundaries_from_csv(csv_path, output_xml_path)

"""# Environment

The previous problem was because of limited number of points especially in the curves, so the solution was to add additional points based on interpolation formula!

## ⚠️ PLEASE NOTE:
This colab runs best using a GPU runtime.  From the Colab menu, choose Runtime > Change Runtime Type, then select **'GPU'** in the dropdown.
"""

# Copyright 2024 The Brax Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# pylint:disable=g-multiple-import

"""Defines a race track environment with a ball."""
try:
  import brax
except ImportError:
  !pip install git+https://github.com/google/brax.git@main
  clear_output()
  import brax

from brax import base
from brax import envs
from brax.envs.base import PipelineEnv, State
from brax.io import mjcf
from etils import epath
import jax
from jax import numpy as jp
import mujoco

class RaceTrack(PipelineEnv):

  def __init__(
      self,
      ctrl_cost_weight=0.5,
      healthy_reward=1.0,
      terminate_when_unhealthy=True,
      reset_noise_scale=0.1,
      exclude_current_positions_from_observation=True,
      backend='mjx',
      **kwargs,
  ):
    path = epath.Path('track_env.xml')
    sys = mjcf.load(path)

    n_frames = 5

    if backend in ['spring', 'positional']:
      sys = sys.tree_replace({'opt.timestep': 0.005})
      n_frames = 10

    if backend == 'mjx':
      sys = sys.tree_replace({
          'opt.solver': mujoco.mjtSolver.mjSOL_NEWTON,
          'opt.disableflags': mujoco.mjtDisableBit.mjDSBL_EULERDAMP,
          'opt.iterations': 1,
          'opt.ls_iterations': 4,
      })

    if backend == 'positional':
      sys = sys.replace(
          actuator=sys.actuator.replace(
              gear=200 * jp.ones_like(sys.actuator.gear)
          )
      )

    kwargs['n_frames'] = kwargs.get('n_frames', n_frames)

    super().__init__(sys=sys, backend=backend, **kwargs)

    self._ctrl_cost_weight = ctrl_cost_weight
    self._healthy_reward = healthy_reward
    self._terminate_when_unhealthy = terminate_when_unhealthy
    self._reset_noise_scale = reset_noise_scale
    self._exclude_current_positions_from_observation = (
        exclude_current_positions_from_observation
    )

  def reset(self, rng: jax.Array) -> State:
    """Resets the environment to an initial state."""
    rng, rng1, rng2 = jax.random.split(rng, 3)

    low, hi = -self._reset_noise_scale, self._reset_noise_scale
    q = self.sys.init_q + jax.random.uniform(
        rng1, (self.sys.q_size(),), minval=low, maxval=hi
    )
    qd = hi * jax.random.normal(rng2, (self.sys.qd_size(),))

    pipeline_state = self.pipeline_init(q, qd)
    obs = self._get_obs(pipeline_state)

    reward, done, zero = jp.zeros(3)
    metrics = {
        'reward_survive': zero,
        'reward_ctrl': zero,
    }
    return State(pipeline_state, obs, reward, done, metrics)

  def step(self, state: State, action: jax.Array) -> State:
    """Run one timestep of the environment's dynamics."""
    pipeline_state0 = state.pipeline_state
    assert pipeline_state0 is not None
    pipeline_state = self.pipeline_step(pipeline_state0, action)

    min_z, max_z = 0.1, 2.0
    is_healthy = jp.where(pipeline_state.x.pos[0, 2] < min_z, 0.0, 1.0)
    is_healthy = jp.where(pipeline_state.x.pos[0, 2] > max_z, 0.0, is_healthy)
    if self._terminate_when_unhealthy:
      healthy_reward = self._healthy_reward
    else:
      healthy_reward = self._healthy_reward * is_healthy
    ctrl_cost = self._ctrl_cost_weight * jp.sum(jp.square(action))

    obs = self._get_obs(pipeline_state)
    reward = healthy_reward - ctrl_cost
    done = 1.0 - is_healthy if self._terminate_when_unhealthy else 0.0
    state.metrics.update(
        reward_survive=healthy_reward,
        reward_ctrl=-ctrl_cost,
    )
    return state.replace(
        pipeline_state=pipeline_state, obs=obs, reward=reward, done=done
    )

  def _get_obs(self, pipeline_state: base.State) -> jax.Array:
    """Observe ball position and velocities."""
    qpos = pipeline_state.q
    qvel = pipeline_state.qd

    if self._exclude_current_positions_from_observation:
      qpos = pipeline_state.q[2:]

    return jp.concatenate([qpos] + [qvel])

import functools
import jax
import os

from datetime import datetime
from jax import numpy as jp
import matplotlib.pyplot as plt

from IPython.display import HTML, clear_output


import flax
from brax import envs
from brax.io import model
from brax.io import json
from brax.io import html
from brax.training.agents.ppo import train as ppo
from brax.training.agents.sac import train as sac

if 'COLAB_TPU_ADDR' in os.environ:
  from jax.tools import colab_tpu
  colab_tpu.setup_tpu()

#@title Load Env { run: "auto" }

env_name = 'race_track'
backend = 'positional'

env = RaceTrack(backend=backend)
state = jax.jit(env.reset)(rng=jax.random.PRNGKey(seed=0))

HTML(html.render(env.sys, [state.pipeline_state]))

"""The orientation of the mass is still not the best, currently it is adjusted with initial estimation, but I have solution on mind, using quaternions and global coordinates. Needs some calculations, which I will get back to once I can detect the collision with walls. Right now I am keen to solve the wall collision detection.

Also the wall thickness and orientation and other properties can be changed in the XML creator.

### From here on they are still under development, the actions take place but not as we want them. They are based on force currently but nevertheless need more adjustments.

## ENVIRONMENT THAT ACCEPTS ACTIONS
"""

# Copyright 2024 The Brax Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# pylint:disable=g-multiple-import

"""Defines a race track environment with a ball."""

from brax import base
from brax.envs.base import PipelineEnv, State
from brax.io import mjcf
from etils import epath
import jax
from jax import numpy as jp
import mujoco

class RaceTrack(PipelineEnv):

  def __init__(
      self,
      ctrl_cost_weight=0.5,
      healthy_reward=1.0,
      terminate_when_unhealthy=True,
      reset_noise_scale=0.1,
      exclude_current_positions_from_observation=True,
      backend='mjx',
      **kwargs,
  ):
    path = epath.Path('track_env.xml')
    sys = mjcf.load(path)

    n_frames = 5

    if backend in ['spring', 'positional']:
      sys = sys.tree_replace({'opt.timestep': 0.005})
      n_frames = 10

    if backend == 'mjx':
      sys = sys.tree_replace({
          'opt.solver': mujoco.mjtSolver.mjSOL_NEWTON,
          'opt.disableflags': mujoco.mjtDisableBit.mjDSBL_EULERDAMP,
          'opt.iterations': 1,
          'opt.ls_iterations': 4,
      })

    if backend == 'positional':
      sys = sys.replace(
          actuator=sys.actuator.replace(
              gear=200 * jp.ones_like(sys.actuator.gear)
          )
      )

    kwargs['n_frames'] = kwargs.get('n_frames', n_frames)

    super().__init__(sys=sys, backend=backend, **kwargs)

  def reset(self, rng: jax.Array) -> State:
    """Resets the environment to an initial state."""
    rng, rng1, rng2 = jax.random.split(rng, 3)

    low, hi = -self._reset_noise_scale, self._reset_noise_scale
    q = self.sys.init_q + jax.random.uniform(
        rng1, (self.sys.q_size(),), minval=low, maxval=hi
    )
    qd = hi * jax.random.normal(rng2, (self.sys.qd_size(),))

    pipeline_state = self.pipeline_init(q, qd)
    obs = self._get_obs(pipeline_state)

    reward, done, zero = jp.zeros(3)
    metrics = {
        'reward_survive': zero,
        'reward_ctrl': zero,
    }
    return State(pipeline_state, obs, reward, done, metrics)

  def step(self, state: State, action: jax.Array) -> State:
    """Run one timestep of the environment's dynamics."""
    pipeline_state0 = state.pipeline_state
    assert pipeline_state0 is not None

    # Applying forces
    forces = jp.array([action[0], action[1], 0.0])
    force_vector = jp.zeros_like(pipeline_state0.qd)
    force_vector = force_vector.at[0:3].set(forces)

    pipeline_state = self.pipeline_step(pipeline_state0, action=force_vector)

    min_z, max_z = 0.1, 2.0
    is_healthy = jp.where(pipeline_state.x.pos[0, 2] < min_z, 0.0, 1.0)
    is_healthy = jp.where(pipeline_state.x.pos[0, 2] > max_z, 0.0, is_healthy)
    if self._terminate_when_unhealthy:
      healthy_reward = self._healthy_reward
    else:
      healthy_reward = self._healthy_reward * is_healthy
    ctrl_cost = self._ctrl_cost_weight * jp.sum(jp.square(action))

    obs = self._get_obs(pipeline_state)
    reward = healthy_reward - ctrl_cost
    done = 1.0 - is_healthy if self._terminate_when_unhealthy else 0.0

    state.metrics.update(
        reward_survive=healthy_reward,
        reward_ctrl=-ctrl_cost,
    )
    return state.replace(
        pipeline_state=pipeline_state, obs=obs, reward=reward, done=done
    )

  def _get_obs(self, pipeline_state: base.State) -> jax.Array:
    """Observe ball position and velocities."""
    qpos = pipeline_state.q
    qvel = pipeline_state.qd

    if self._exclude_current_positions_from_observation:
      qpos = pipeline_state.q[2:]

    return jp.concatenate([qpos] + [qvel])

env_name = 'race_track'
backend = 'positional'

env = RaceTrack(backend=backend)
state = jax.jit(env.reset)(rng=jax.random.PRNGKey(seed=0))

HTML(html.render(env.sys, [state.pipeline_state]))

"""## CONTACT DETECTION"""

# Copyright 2024 The Brax Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# pylint:disable=g-multiple-import

"""Defines a race track interactive with a block representing the car"""

from brax import base
from brax import envs
from brax.envs.base import PipelineEnv, State
from brax.io import mjcf
from etils import epath
import jax
from jax import numpy as jp
import mujoco
from contact import get as get_contacts

class RaceTrack(PipelineEnv):

  def __init__(
      self,
      ctrl_cost_weight=0.5,
      healthy_reward=1.0,
      terminate_when_unhealthy=True,
      reset_noise_scale=0.1,
      exclude_current_positions_from_observation=True,
      backend='generalized',
      **kwargs,
  ):
    path = epath.Path('track_env.xml')
    sys = mjcf.load(path)

    n_frames = 5

    if backend in ['spring', 'positional']:
      sys = sys.tree_replace({'opt.timestep': 0.005})
      n_frames = 10

    if backend == 'mjx':
      sys = sys.tree_replace({
          'opt.solver': mujoco.mjtSolver.mjSOL_NEWTON,
          'opt.disableflags': mujoco.mjtDisableBit.mjDSBL_EULERDAMP,
          'opt.iterations': 1,
          'opt.ls_iterations': 4,
      })

    if backend == 'positional':
      sys = sys.replace(
          actuator=sys.actuator.replace(
              gear=200 * jp.ones_like(sys.actuator.gear)
          )
      )

    kwargs['n_frames'] = kwargs.get('n_frames', n_frames)

    super().__init__(sys=sys, backend=backend, **kwargs)

    self._ctrl_cost_weight = ctrl_cost_weight
    self._healthy_reward = healthy_reward
    self._terminate_when_unhealthy = terminate_when_unhealthy
    self._reset_noise_scale = reset_noise_scale
    self._exclude_current_positions_from_observation = (
        exclude_current_positions_from_observation
    )

  def reset(self, rng: jax.Array) -> State:
    """Resets the environment to an initial state."""
    rng, rng1, rng2 = jax.random.split(rng, 3)

    low, hi = -self._reset_noise_scale, self._reset_noise_scale
    q = self.sys.init_q + jax.random.uniform(
        rng1, (self.sys.q_size(),), minval=low, maxval=hi
    )
    qd = hi * jax.random.normal(rng2, (self.sys.qd_size(),))

    pipeline_state = self.pipeline_init(q, qd)
    obs = self._get_obs(pipeline_state)

    reward, done, zero = jp.zeros(3)
    metrics = {
        'reward_survive': zero,
        'reward_ctrl': zero,
        'contact_with_wall': zero,
    }
    return State(pipeline_state, obs, reward, done, metrics)

  def step(self, state: State, action: jax.Array) -> State:
    """Run one timestep of the environment's dynamics."""
    pipeline_state0 = state.pipeline_state
    assert pipeline_state0 is not None
    pipeline_state = self.pipeline_step(pipeline_state0, action)

    min_z, max_z = 0.1, 2.0
    is_healthy = jp.where(pipeline_state.x.pos[0, 2] < min_z, 0.0, 1.0)
    is_healthy = jp.where(pipeline_state.x.pos[0, 2] > max_z, 0.0, is_healthy)
    if self._terminate_when_unhealthy:
      healthy_reward = self._healthy_reward
    else:
      healthy_reward = self._healthy_reward * is_healthy
    ctrl_cost = self._ctrl_cost_weight * jp.sum(jp.square(action))

    obs = self._get_obs(pipeline_state)
    reward = healthy_reward - ctrl_cost
    done = 1.0 - is_healthy if self._terminate_when_unhealthy else 0.0

    # Detect contact with the walls
    contacts = get_contacts(self.sys, pipeline_state.x)
    contact_with_wall = 0.0
    if contacts is not None:
      contact_with_wall = jp.any(contacts.link_idx[1] == 0).astype(jp.float32)

    state.metrics.update(
        reward_survive=healthy_reward,
        reward_ctrl=-ctrl_cost,
        contact_with_wall=contact_with_wall,
    )
    return state.replace(
        pipeline_state=pipeline_state, obs=obs, reward=reward, done=done
    )

  def _get_obs(self, pipeline_state: base.State) -> jax.Array:
    """Observe ball position and velocities."""
    qpos = pipeline_state.q
    qvel = pipeline_state.qd

    if self._exclude_current_positions_from_observation:
      qpos = pipeline_state.q[2:]

    return jp.concatenate([qpos] + [qvel])

"""## Testing Movement

"""

from brax import base
from brax import math
from brax.envs.base import PipelineEnv, State
from brax.io import mjcf
from etils import epath
import jax
from jax import numpy as jp

class BallTrackEnv(PipelineEnv):
  def __init__(self, backend='generalized', **kwargs):
    path = epath.Path('track_env.xml')
    sys = mjcf.load(path)

    n_frames = 5
    if backend in ['spring', 'positional']:
      sys = sys.tree_replace({'opt.timestep': 0.001})
      n_frames = 50

    kwargs['n_frames'] = kwargs.get('n_frames', n_frames)
    super().__init__(sys=sys, backend=backend, **kwargs)

  def reset(self, rng: jax.Array) -> State:
    qpos = self.sys.init_q
    qvel = jax.random.uniform(rng, (self.sys.qd_size(),), minval=-0.005, maxval=0.005)

    pipeline_state = self.pipeline_init(qpos, qvel)
    obs = self._get_obs(pipeline_state)
    reward, done, zero = jp.zeros(3)
    metrics = {
      'reward_forward': zero,
      'reward_survive': zero,
      'reward_ctrl': zero,
      'reward_contact': zero,
      'x_position': zero,
      'y_position': zero,
      'distance_from_origin': zero,
      'x_velocity': zero,
      'y_velocity': zero,
      'forward_reward': zero,
    }
    return State(pipeline_state, obs, reward, done, metrics)

  def step(self, state: State, action: jax.Array) -> State:
    pipeline_state0 = state.pipeline_state
    assert pipeline_state0 is not None
    pipeline_state = self.pipeline_step(pipeline_state0, action)

    velocity = (pipeline_state.x.pos[0] - pipeline_state0.x.pos[0]) / self.dt
    forward_reward = velocity[0]

    obs = self._get_obs(pipeline_state)
    reward = forward_reward
    done = 0.0

    contact = self._detect_collision(pipeline_state)
    if contact:
      done = 1.0

    state.metrics.update(
      reward_forward=forward_reward,
      reward_survive=0.0,
      reward_ctrl=0.0,
      reward_contact=0.0,
      x_position=pipeline_state.x.pos[0, 0],
      y_position=pipeline_state.x.pos[0, 1],
      distance_from_origin=math.safe_norm(pipeline_state.x.pos[0]),
      x_velocity=velocity[0],
      y_velocity=velocity[1],
      forward_reward=forward_reward,
    )
    return state.replace(pipeline_state=pipeline_state, obs=obs, reward=reward, done=done)

  def _get_obs(self, pipeline_state: base.State) -> jax.Array:
    """Observe ball position and velocities."""
    qpos = pipeline_state.q
    qvel = pipeline_state.qd
    return jp.concatenate([qpos, qvel])

  def _detect_collision(self, pipeline_state: base.State) -> bool:
    """Detect collision of the ball with walls."""
    contacts = pipeline_state.contact
    if contacts:
      for contact in contacts:
        if contact.dist < 0.0:
          return True
    return False

rng = jax.random.PRNGKey(0)
env = BallTrackEnv()
state = env.reset(rng)
print("Initial Ball Position:", state.pipeline_state.x.pos[0])

action = jp.array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])
next_state = env.step(state, action)
print("Next Ball Position:", next_state.pipeline_state.x.pos[0])

from brax import base
from brax import math
from brax.envs.base import PipelineEnv, State
from brax.io import mjcf
from etils import epath
import jax
from jax import numpy as jp

class BallTrackEnv(PipelineEnv):
  def __init__(self, backend='generalized', **kwargs):
    path = epath.Path('track_env.xml')
    sys = mjcf.load(path)

    n_frames = 5
    if backend in ['spring', 'positional']:
      sys = sys.tree_replace({'opt.timestep': 0.001})
      n_frames = 50

    kwargs['n_frames'] = kwargs.get('n_frames', n_frames)
    super().__init__(sys=sys, backend=backend, **kwargs)

  def reset(self, rng: jax.Array) -> State:
    qpos = self.sys.init_q
    qvel = jax.random.uniform(rng, (self.sys.qd_size(),), minval=-0.005, maxval=0.005)

    pipeline_state = self.pipeline_init(qpos, qvel)
    obs = self._get_obs(pipeline_state)
    reward, done, zero = jp.zeros(3)
    metrics = {
      'reward_forward': zero,
      'reward_survive': zero,
      'reward_ctrl': zero,
      'reward_contact': zero,
      'x_position': zero,
      'y_position': zero,
      'distance_from_origin': zero,
      'x_velocity': zero,
      'y_velocity': zero,
      'forward_reward': zero,
    }
    return State(pipeline_state, obs, reward, done, metrics)

  def step(self, state: State, action: jax.Array) -> State:
    pipeline_state0 = state.pipeline_state
    assert pipeline_state0 is not None
    pipeline_state = self.pipeline_step(pipeline_state0, action)

    velocity = (pipeline_state.x.pos[0] - pipeline_state0.x.pos[0]) / self.dt
    forward_reward = velocity[0]

    obs = self._get_obs(pipeline_state)
    reward = forward_reward
    done = 0.0

    contact = self._detect_collision(pipeline_state)
    if contact:
      done = 1.0
      print("Collision detected!")

    state.metrics.update(
      reward_forward=forward_reward,
      reward_survive=0.0,
      reward_ctrl=0.0,
      reward_contact=0.0,
      x_position=pipeline_state.x.pos[0, 0],
      y_position=pipeline_state.x.pos[0, 1],
      distance_from_origin=math.safe_norm(pipeline_state.x.pos[0]),
      x_velocity=velocity[0],
      y_velocity=velocity[1],
      forward_reward=forward_reward,
    )
    return state.replace(pipeline_state=pipeline_state, obs=obs, reward=reward, done=done)

  def _get_obs(self, pipeline_state: base.State) -> jax.Array:
    """Observe ball position and velocities."""
    qpos = pipeline_state.q
    qvel = pipeline_state.qd
    return jp.concatenate([qpos, qvel])

  def _detect_collision(self, pipeline_state: base.State) -> bool:
    """Detect collision of the ball with walls."""
    contacts = pipeline_state.contact
    if contacts:
      for contact in contacts:
        if contact.dist < 0.0:
          return True
    return False

rng = jax.random.PRNGKey(0)
env = BallTrackEnv()
state = env.reset(rng)
print("Initial Ball Position:", state.pipeline_state.x.pos[0])

for i in range(10):  # Number of steps
    action = jp.array([0.1, 0, 0.0, 0.0, 0.0, 0.0])
    state = env.step(state, action)
    print(f"Step {i+1} Ball Position:", state.pipeline_state.x.pos[0])
    if state.done:
        break

from brax import base
from brax import math
from brax.envs.base import PipelineEnv, State
from brax.io import mjcf
from etils import epath
import jax
from jax import numpy as jp

class MassAndTrack(PipelineEnv):

  def __init__(self, backend='mjx', **kwargs):