import mujoco
import numpy as np
import matplotlib.pyplot as plt
import os

def main():
    xml_path = os.path.join(os.path.dirname(__file__), '../assets/virtual_test_rig.xml')
    model = mujoco.MjModel.from_xml_path(xml_path)
    data = mujoco.MjData(model)

    vel_x_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_ACTUATOR, 'drive_x')
    spin_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_ACTUATOR, 'drive_spin')
    load_z_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_ACTUATOR, 'load_z')

    # Simulation parameters
    Vx = 10.0 # m/s
    R = 0.3   # m
    
    # Warmup / Settle (1 second)
    for _ in range(int(1.0 / model.opt.timestep)):
        data.ctrl[load_z_id] = -3000 # 3000N downward force
        data.ctrl[vel_x_id] = Vx
        data.ctrl[spin_id] = Vx / R # pure rolling
        mujoco.mj_step(model, data)

    # Sweep longitudinal slip over 4 seconds
    timesteps = int(4.0 / model.opt.timestep)
    kappas = np.linspace(-0.3, 0.3, timesteps)
    fx_list = []
    
    for kappa in kappas:
        # Standard SAE longitudinal slip definition kinematics
        # omega = Vx * (1 + kappa) / R
        omega = Vx * (1 + kappa) / R
        
        data.ctrl[load_z_id] = -3000
        data.ctrl[vel_x_id] = Vx
        data.ctrl[spin_id] = omega
        
        mujoco.mj_step(model, data)
        
        # The force the tire exerts on the ground in X is countered by the drive_x actuator
        # If tire pulls the carriage forward, drive_x force is negative to maintain Vx
        # So Fx_tire = - drive_x_actuator_force 
        fx_tire = -data.actuator_force[vel_x_id]
        fx_list.append(fx_tire)

    # Plot
    plt.figure(figsize=(8,6))
    plt.plot(kappas, fx_list, label='MuJoCo Frictional Contact', color='red', linewidth=2)
    plt.title("Phase 1: Baseline Slip Curve (MuJoCo Default Point Contact)")
    plt.xlabel(r"Longitudinal Slip Ratio $\kappa$")
    plt.ylabel("Longitudinal Target Force $F_x$ (N)")
    plt.grid(True)
    plt.legend()
    
    # Save the figure to the artifacts directory so the user can see it!
    out_path = '/home/bairg/.gemini/antigravity/brain/6385003a-6149-4681-9d39-23275836c39b/baseline_fx.png'
    plt.savefig(out_path)
    print(f"Saved baseline slip plot to {out_path}")
    
    # ---------------------------------------------------------
    # Sweep lateral slip angle over 4 seconds
    # ---------------------------------------------------------
    steer_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_ACTUATOR, 'set_steer')
    vel_y_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_ACTUATOR, 'drive_y')
    
    # Re-settle
    for _ in range(int(1.0 / model.opt.timestep)):
        data.ctrl[load_z_id] = -3000
        data.ctrl[vel_x_id] = Vx
        data.ctrl[vel_y_id] = 0
        data.ctrl[steer_id] = 0
        data.ctrl[spin_id] = Vx / R
        mujoco.mj_step(model, data)

    alphas = np.linspace(-np.radians(15), np.radians(15), timesteps)
    fy_list = []
    
    for alpha in alphas:
        data.ctrl[load_z_id] = -3000
        data.ctrl[vel_x_id] = Vx
        data.ctrl[vel_y_id] = 0
        data.ctrl[steer_id] = alpha
        # pure rolling condition: V_longitudinal_wheel = Vx * cos(alpha)
        data.ctrl[spin_id] = Vx * np.cos(alpha) / R 
        
        mujoco.mj_step(model, data)
        
        # The lateral force generated by the tire in world Y is countered by drive_y
        fy_world = -data.actuator_force[vel_y_id]
        fy_list.append(fy_world)

    plt.figure(figsize=(8,6))
    plt.plot(np.degrees(alphas), fy_list, label='MuJoCo Frictional Contact', color='blue', linewidth=2)
    plt.title("Phase 1: Baseline Lateral Curve (MuJoCo Default Point Contact)")
    plt.xlabel(r"Slip Angle $\alpha$ (degrees)")
    plt.ylabel("Lateral Target Force $F_y$ (N)")
    plt.grid(True)
    plt.legend()
    
    out_path_fy = '/home/bairg/.gemini/antigravity/brain/6385003a-6149-4681-9d39-23275836c39b/baseline_fy.png'
    plt.savefig(out_path_fy)
    print(f"Saved baseline lateral plot to {out_path_fy}")

if __name__ == '__main__':
    main()
